name: Pipeline Exemplo

on: 
  push:
    branches:
      - main

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Exibir Mensagem de Teste 1
        run: echo "Hello, World!"

      - name: Exibir Mensagem de Teste 2
        run: echo "Executando teste"

  build:
    runs-on: ubuntu-latest
    needs: teste  # Garante que o job 'teste' seja concluído antes
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Exibir Mensagem de Build
        run: echo "Executando build"

      # Exemplo de uso de ambiente para compartilhar variáveis (opcional)
      - name: Configurar Variável de Ambiente
        run: echo "BUILD_ENV=production" >> $GITHUB_ENV

      # Exemplo de step condicional (executar apenas se estiver na branch main)
      - name: Executar Ação Específica na Branch Main
        if: github.ref == 'refs/heads/main'
        run: echo "Deploy ou outra ação para branch main"
